### ISSUE TITLE
How to get detail  action

### ISSUE THREAD

**Issue by xuyifan-0731** [AndroidArenaAgent/AndroidArena#3]
Hi！ Thanks for your impressive work. 
In the example you gave,actions similar to the following format is provided
```
action_seq:
      - d.app_start('com.google.android.calendar')
      - d.xpath('//*[@resource-id="com.google.android.calendar:id/floating_action_button"]').click()
      - d.xpath('//*[@resource-id="com.google.android.calendar:id/floating_action_button"]').click()
      - d.xpath('//*[@resource-id="com.google.android.calendar:id/title"]').set_text('meeting')
      - d.xpath('//*[@resource-id="com.google.android.calendar:id/expanded_recycler"]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]').click()
      - d.xpath('//*[@resource-id="android:id/next"]').click()
      - d.xpath('//*[@text="13"]').click()
      - d.xpath('//*[@resource-id="android:id/button1"]').click()
      - d.swipe_ext('up')
      - d.xpath('//*[@resource-id="com.google.android.calendar:id/expanded_recycler"]/android.widget.Button[2]').click()
      - d.xpath('//*[@resource-id="com.google.android.calendar:id/search_text"]').set_text('Microsoft SVC Building')
      - d.xpath('//*[@resource-id="com.google.android.calendar:id/suggestions"]/android.widget.Button[1]').click()
      - d.xpath('//*[@resource-id="com.google.android.calendar:id/save"]').click()
```
My question is how to get the xpath you defined from the mobile phone? I only know that I can use the adb command to get the main activity, which is the com.google.android.calendar part. According to your article, building a complete action is important for evaluation.

**Comment by xmzzyo** [comment]
hi,

you can easily get the XPath through [Weditor](https://github.com/alibaba/web-editor).

Here is an example:
![image](https://github.com/AndroidArenaAgent/AndroidArena/assets/35603565/335e7f5c-2572-4fbb-8def-06afe62575ba)

The XPath is in the `XPathLite` field, and you can execute the action sequence in the `Coding` frame.
